createChannel is done, config file is added
RightMesh/microraiden-java pull request #1
Opened 2018-01-04 00:42 UTC by comey

2018-01-04 01:09 UTC, cfoo commented on david1.pkey
> +{"privkey":"7acd94881a99081e12ea19301eabfd46643dd9e01148747ec1e49b9f9d8ba514","address":"17881407d62a352935445ec4344f988204e84716"}
Put these keys in a configuration container?
https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ConfigurationContainer.html

2018-01-04 01:09 UTC, fractalic requested changes
Comments on the MicroRaiden class functions would be very helpful :P

2018-01-04 01:17 UTC, cfoo commented on src/main/java/MicroRaiden.java
> +    private static final int INTERVAL_CHECK_TRANS_DONE=100;
Use a builder pattern to instantiate and set these values

2018-01-04 02:35 UTC, compscidr commented on .gitignore
> -*.pkey
This is probably how your pkey ended up getting committed - prob want to not take this out of the gitignore ;)

2018-01-04 02:39 UTC, compscidr commented on src/main/java/MicroRaiden.java
> +    	if(privateKeyHex.startsWith("0x")) {
indenting is a bit messed up here - also the try catch blocks down a bit farther should have consistent spacing with the other try catch blocks (space between try and { and catch and { for example)

2018-01-04 02:41 UTC, compscidr commented on src/main/java/MicroRaiden.java
> +    public void createChannel(String senderAccountName, String receiverAccountID, String deposit) {
prob would be better to have the deposit be an int / float or whatever and then do a proper conversion from the arg handling function. In the longer run when people will be using this function in their own code I doubt they'll want to deal with token values as strings.

2018-01-04 02:42 UTC, compscidr commented on src/main/java/MicroRaiden.java
> +    private static byte[] concatenateByteArrays(byte[]... arrays)
Can we move this function out into a helper class or something?

2018-01-04 02:43 UTC, compscidr commented on src/main/java/MicroRaiden.java
> +    private String getHttpResponse(String requestString) throws IOException{
Similarly we may wish to move this function into either a helper class, or maybe one dedicated just to http / network comms. or something.

2018-01-04 02:45 UTC, compscidr commented on src/main/java/MicroRaiden.java
> +    public void getEtherBalance(String accountName){
Might want to think about organizing things like this into a Wallet-like class or Ethereum class  (getting balances, reading account files, etc.) and then keep the Raiden class dealing strictly with interacting with the channels (and calling the functions from that class).

2018-01-10 18:41 UTC, sriks1 commented on src/main/java/MicroRaiden.java
> +    private final Object lockRunning = new Object();
we can remove the commented code.

2018-01-10 18:44 UTC, sriks1 commented on src/main/java/MicroRaiden.java
> +		if(receiverAddressBytes.length!=20) {
define variables for the magic numbers.

2018-01-10 18:52 UTC, sriks1 commented on src/main/java/MicroRaiden.java
> +    public void buyToken(String accountName,String amountOfEther){
edge cases for the parameters.

2018-01-10 18:56 UTC, sriks1 commented on src/main/java/MicroRaiden.java
> +    private static String prependingZeros(String hexString, int totalWidth) {
functions like these go into utility class?

2018-01-12 00:35 UTC, merged